version: '3.8'
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: cybage@123
      POSTGRES_DB: laravel_docker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5400:5432'
 
  php-apache:
    container_name: php-apache
      #image: laravel-docker_php-apache
    build:
      context: ./php
    ports:
        - '8200:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database

